import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './global.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nikolaj Rask Portolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{overflowX: 'hidden', background: 'black'}}>{children}</body>
    </html>
  );
}
